#!/usr/bin/env python3
"""Convert the repository qrcode SVG to OpenSCAD module data.

Why this exists:
The qrcode-generated SVG contains a white background rectangle. OpenSCAD's SVG
import is geometry-based and ignores fill color, so importing qr.svg directly
turns the QR into a solid square. This script extracts only the black modules
and writes qr_data.scad, which rack.scad consumes directly.

No third-party Python packages are required.
"""
from __future__ import annotations

import argparse
import math
import xml.etree.ElementTree as ET
from pathlib import Path

XLINK = "http://www.w3.org/1999/xlink"


def number(value: str | None) -> float:
    if value is None:
        raise ValueError("missing numeric SVG attribute")
    return float(value.strip().replace("px", ""))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", nargs="?", default="qr.svg")
    parser.add_argument("output", nargs="?", default="qr_data.scad")
    args = parser.parse_args()

    src = Path(args.input)
    dst = Path(args.output)
    root = ET.parse(src).getroot()

    view_box = root.attrib.get("viewBox")
    if view_box:
        _, _, vb_w, vb_h = map(float, view_box.split())
    else:
        vb_w = number(root.attrib.get("width"))
        vb_h = number(root.attrib.get("height"))

    prototype = next(
        (e for e in root.iter() if e.tag.endswith("rect") and e.attrib.get("id") == "p"),
        None,
    )
    if prototype is None:
        raise SystemExit("qr.svg does not contain the expected <rect id='p'> module prototype")

    cell_w = number(prototype.attrib.get("width"))
    cell_h = number(prototype.attrib.get("height"))
    if not math.isclose(cell_w, cell_h, rel_tol=1e-6):
        raise SystemExit("QR modules are not square")

    grid_x = int(round(vb_w / cell_w))
    grid_y = int(round(vb_h / cell_h))
    if grid_x != grid_y:
        raise SystemExit(f"QR viewBox is not square: {grid_x} x {grid_y}")

    modules: list[tuple[int, int]] = []
    for e in root.iter():
        if not e.tag.endswith("use"):
            continue
        href = e.attrib.get(f"{{{XLINK}}}href") or e.attrib.get("href")
        fill = e.attrib.get("fill", "#000000").strip().lower()
        if href != "#p" or fill in {"#ffffff", "white", "none"}:
            continue
        x = int(round(number(e.attrib.get("x")) / cell_w))
        y = int(round(number(e.attrib.get("y")) / cell_h))
        modules.append((x, y))

    if not modules:
        raise SystemExit("No QR modules found")

    lines = [
        "// AUTO-GENERATED by tools/prepare_qr.py — do not edit by hand.",
        "qr_ready = true;",
        f"qr_grid = {grid_x};",
        "qr_modules = [",
    ]
    lines += [f"    [{x}, {y}]," for x, y in modules]
    lines += ["];", ""]
    dst.write_text("\n".join(lines), encoding="utf-8")

    module_mm = 30.0 / grid_x
    print(f"Generated {dst} from {src}")
    print(f"grid={grid_x}x{grid_x}, black_modules={len(modules)}, 30mm QR module≈{module_mm:.3f}mm")


if __name__ == "__main__":
    main()
